/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Service disponible */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example ok */
                            status?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Inscription (téléphone + OTP simulé en dev) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example 0700000000 */
                        telephone: string;
                        nom: string;
                        prenom: string;
                    };
                };
            };
            responses: {
                /** @description OTP envoyé */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                422: components["responses"]["ValidationFailed"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify-otp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Vérifie l'OTP → délivre un token Bearer (compte de niveau « base ») */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example +2250700000000 */
                        telephone: string;
                        /** @example 123456 */
                        code: string;
                        /** @enum {string} */
                        but?: "inscription" | "connexion" | "recuperation";
                    };
                };
            };
            responses: {
                /** @description Téléphone vérifié */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResponse"];
                    };
                };
                422: components["responses"]["ValidationFailed"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Connexion téléphone + mot de passe (compte vérifié) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example +2250700000000 */
                        telephone: string;
                        /** Format: password */
                        password: string;
                    };
                };
            };
            responses: {
                /** @description Authentifié (AuthResponse) ; OU, si le compte doit présenter un second facteur (MFA « prêt à activer », gate config), un défi MfaChallenge SANS token Bearer. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResponse"] | components["schemas"]["MfaChallenge"];
                    };
                };
                /** @description Compte non vérifié */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                422: components["responses"]["ValidationFailed"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/mfa/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 2e étape de connexion — vérifie le second facteur et délivre le token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description Jeton de défi reçu de /auth/login */
                        mfa_token: string;
                        /**
                         * @description Code TOTP à 6 chiffres
                         * @example 123456
                         */
                        code: string;
                    };
                };
            };
            responses: {
                /** @description Second facteur validé */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResponse"];
                    };
                };
                422: components["responses"]["ValidationFailed"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/mfa/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** État MFA du compte connecté (le front l'AFFICHE, ne le déduit pas) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description État MFA */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MfaStatus"];
                    };
                };
                /** @description Non authentifié */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/mfa/enroll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Démarre l'enrôlement TOTP (renvoie le secret + l'URI otpauth:// pour le QR) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Secret généré (à confirmer par un premier code) */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example totp */
                            type?: string;
                            /** @description Secret base32 — affiché une seule fois */
                            secret?: string;
                            /** @example otpauth://totp/MaSante:+2250700000000?secret=...&issuer=MaSante */
                            otpauth_uri?: string;
                        };
                    };
                };
                /** @description Non authentifié */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/mfa/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirme l'enrôlement avec le premier code de l'application d'authentification */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example 123456 */
                        code: string;
                    };
                };
            };
            responses: {
                /** @description Second facteur activé */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                422: components["responses"]["ValidationFailed"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/mfa": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Désactive le second facteur du compte connecté */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Second facteur désactivé */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Non authentifié */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Profil de l'utilisateur authentifié (avec ses rôles RBAC) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Profil */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            user?: components["schemas"]["User"];
                        };
                    };
                };
                /** @description Non authentifié */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        User: {
            id?: number;
            nom?: string;
            prenom?: string;
            telephone?: string;
            /** Format: date-time */
            telephone_verified_at?: string | null;
            /** @description Rôles RBAC fournis par le backend (CDC_10 §3.6). Le mobile n'utilise que « patient ». */
            roles?: string[];
        };
        AuthResponse: {
            message?: string;
            token?: string;
            /** @example Bearer */
            token_type?: string;
            user?: components["schemas"]["User"];
        };
        /** @description Défi renvoyé par /auth/login quand un second facteur est exigé (aucun token). */
        MfaChallenge: {
            /** @example true */
            mfa_required?: boolean;
            /** @description À renvoyer à /auth/mfa/verify (courte durée de vie) */
            mfa_token?: string;
            message?: string;
        };
        /** @description État MFA fourni par le backend (autorité) ; le front l'affiche seulement. */
        MfaStatus: {
            /** @description Exigence MFA globale active (gate config) */
            enforce?: boolean;
            /** @description Le rôle du compte impose la MFA (CDC_10 §3.5) */
            oblige_pour_ce_compte?: boolean;
            /** @description Un second facteur est confirmé */
            facteur_confirme?: boolean;
            /** @description Obligé mais pas encore configuré → onboarding MFA */
            doit_configurer?: boolean;
        };
    };
    responses: {
        /** @description Données invalides */
        ValidationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    error?: {
                        /** @example VALIDATION_FAILED */
                        code?: string;
                        message?: string;
                        request_id?: string;
                    };
                };
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
